AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Questions and answers project
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  Env:
    Type: String
    Default: dev
  S3BucketName:
    Type: String
    Default: questions-answers
  CognitoUserPoolName:
    Type: String
    Default: questions-answers
  CognitoWebClientName:
    Type: String
    Default: qa-webclient
Resources:
  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Origin Access Identity'

 CloudFrontOAC:
  Type: "AWS::CloudFront::OriginAccessControl"
  Properties:
    OriginAccessControlConfig:
      Name: "dev-questions-answer.s3.sa-east-1.amazonaws.com"
      Description: "OAC for CloudFront to access S3"
      SigningBehavior: always
      OriginAccessControlOriginType: s3
      SigningProtocol: sigv4

  CloudfrontDistribution:
  
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - Id: s3-website
            DomainName: !GetAtt S3Bucket.DomainName
            S3OriginConfig:
              OriginAccessControlId: !Ref CloudFrontOAC
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          Compress: true

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Env}-${S3BucketName}"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${Env}-${S3BucketName}/*"
            Principal: "*"
            Condition:
              StringEquals:
                "aws:UserAgent": "Amazon CloudFront"

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${Env}-${CognitoUserPoolName}"
      AliasAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
